# Generated by Django 3.0.9 on 2022-01-07 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_education_employmentdetail_personaldetail_social_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonalinfo',
            name='job_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpersonalinfo',
            name='other_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.UserPersonalInfo'),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userpersonalinfo',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='PersonalDetail',
        ),
    ]
