# Generated by Django 3.0.9 on 2022-01-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_auto_20220110_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.UserPersonalInfo'),
        ),
    ]
