# Generated by Django 3.0.9 on 2022-01-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_auto_20220110_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.UserPersonalInfo'),
        ),
    ]
