# Generated by Django 3.0.9 on 2022-01-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_auto_20220111_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userSkills',
            new_name='UserSkill',
        ),
    ]
