# Generated by Django 3.0.9 on 2022-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_auto_20220111_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
