# Generated by Django 3.0.9 on 2022-01-11 18:00

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_userpersonalinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdetail',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
