# Generated by Django 3.0.9 on 2022-01-11 18:02

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0019_employmentdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetail',
            name='country',
            field=django_countries.fields.CountryField(default='USA', max_length=2),
        ),
    ]
