# Generated by Django 3.0.9 on 2022-01-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentdetail',
            name='country',
        ),
    ]
